# Generated by Django 4.1.6 on 2023-09-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=255)),
                ('directed_by', models.CharField(default='Unknown', max_length=255)),
                ('starring', models.CharField(default='N/A', max_length=255)),
                ('language', models.CharField(default='English', max_length=100)),
                ('theaters', models.CharField(default='N/A', max_length=255)),
                ('location', models.CharField(default='N/A', max_length=255)),
                ('image', models.URLField()),
            ],
        ),
    ]
